[{"ContainerToolsException.Message":"Error response from daemon: Cannot kill container: d3332ea3c03ce39706ead81e636ff368f9713003549c3b8569efc1baa1922074: Container d3332ea3c03ce39706ead81e636ff368f9713003549c3b8569efc1baa1922074 is not running","ContainerToolsException.ErrorCode":"DT1001","ContainerToolsException.StackTrace":"   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__31.MoveNext()\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__38.MoveNext()","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.CommandLine.Program":"docker-compose","ContainerToolsException.CommandLine.TelemetrySafeArguments":"","ContainerToolsException.CommandLine.ExitCode":"1","ContainerToolsException.CommandLine.ErrorOutput":"Container dockercompose12759433780747928888-validateid.api-1  Killing\r\nContainer dockercompose12759433780747928888-validateid.api-1  Error while Killing\r\nError response from daemon: Cannot kill container: d3332ea3c03ce39706ead81e636ff368f9713003549c3b8569efc1baa1922074: Container d3332ea3c03ce39706ead81e636ff368f9713003549c3b8569efc1baa1922074 is not running"}]